Test with PR (#1)
* Test with PR

* Test with PR

* Try with json

diff --git a/.github/workflows/tab-analitics.yaml b/.github/workflows/tab-analitics.yaml
--- a/.github/workflows/tab-analitics.yaml
+++ b/.github/workflows/tab-analitics.yaml
@@ -12,22 +12,24 @@ jobs:
         uses: jitterbit/get-changed-files@v1
         id: files
         with:
-          format: space-delimited
+          format: 'json'
           token: ${{ secrets.GITHUB_TOKEN }}  
       - run: | 
               echo "List of changed files got succesfully"
-              echo "${{ steps.files.outputs.all }}"      
+              echo "${{ steps.files.outputs.all }}"
   find-tabs:
     needs: find-changed-files
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        changed-files: ["${{ needs.find-changed-files.outputs.files }}"] 
+        changed-files: ${{fromJson(needs.find-changed-files.outputs.files)}}
+      fail-fast: false
     steps:
       - uses: actions/checkout@v2.1.0
       - name: Find tabs
         run: |
-              cat ${{matrix.changed-files}} | grep "   " > ${{matrix.changed-files}}.log 2>&1
+              echo "${{matrix.changed-files}}"
+              cat ${{matrix.changed-files}} | grep -P "\t" > ${{matrix.changed-files}}.log 2>&1 || echo "Tabs not found"
       - name: Upload report
         uses: actions/upload-artifact@v2
         with:
